### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by azigoldstein** [leroy0211/form-redux-checkbox-group#5]
Great Package! Thank you so much.

Just wanted to point out a mistake in the documentation

![image](https://user-images.githubusercontent.com/33836715/50612763-3308fe00-0ea9-11e9-92a0-0e3f51b9ac60.png)

`labelField` should be `textField`

**Comment by leroy0211** [comment]
I've updated the code instead of the documentation. The documentation was actually correct about it, but the code was wrong. 

I'll create a new minor version of it.
